on: push

jobs:
  pnpm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/setup@v1
        with:
        version: 11
        runtime: node@22
        cache: true
      - run: pnpm --version
      - run: pnpm build
