on: push

jobs:
  pnpm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/setup@v1
        with:
          version: 11
          runtime: node@22
          cache: true
      - run: pnpm install
        env:
          PNPM_CONFIG_MINIMUM_RELEASE_AGE: 0
      - run: pnpm --version
      - run: pnpm build
