name: 打包React項目

on: push

jobs:
  pnpm-build:
    runs-on: ubuntu-latest
    steps:
      - name: 把程式碼放入執行環境
        uses: actions/checkout@v6

      - name: 設定pnpm
        uses: pnpm/setup@v1
        with:
          version: 11
          runtime: node@22
          cache: true
      #     install: false

      # - name: 手動安裝
      #   run: pnpm install

      - name: 編譯
        run: pnpm build

      - name: 部署
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
